---
title: "Getting New Data Clean Project"
author: "Dimas Adinugroho"
date: "24 Mei 2016"
output: html_document
---

## Code Book

Code Book ini merupakan summary dari data field pada file tidy.txt

Menggunakan **x_train, y_train, subject_train** file pada folder train dan **x_test, y_test,  subject_test** pada folder test.
subject mengacu pada orang yang sedang diteliti. Hasil dari **tidy.txt** merupakan average measure(mean) dari tiap subject dan activitynya (30 subject * 6 activities = 180 baris)
  
**activity_label.txt** berisikan 6 activity yang dilakukan saat memegang smartphones. di identifikasikan dengan value 1:6.

**features.txt** berisikan **mean** dan **standard deviasi** untuk berbagai variable atau posisi tubuh dalam bidang X,Y dan Z saat memegang smartphones. 

##features.txt 
* tBodyAccMeanX
* tBodyAccMeanY
* tBodyAccMeanZ
* tBodyAccStdX
* tBodyAccStdY
* tBodyAccStdZ
* tGravityAccMeanX
* tGravityAccMeanY
* tGravityAccMeanZ
* tGravityAccStdX
* tGravityAccStdY
* tGravityAccStdZ
* tBodyAccJerkMeanX
* tBodyAccJerkMeanY
* tBodyAccJerkMeanZ
* tBodyAccJerkStdX
* tBodyAccJerkStdY
* tBodyAccJerkStdZ
* tBodyGyroMeanX
* tBodyGyroMeanY
* tBodyGyroMeanZ
* tBodyGyroStdX
* tBodyGyroStdY
* tBodyGyroStdZ
* tBodyGyroJerkMeanX
* tBodyGyroJerkMeanY
* tBodyGyroJerkMeanZ
* tBodyGyroJerkStdX
* tBodyGyroJerkStdY
* tBodyGyroJerkStdZ
* tBodyAccMagMean
* tBodyAccMagStd
* tGravityAccMagMean
* tGravityAccMagStd
* tBodyAccJerkMagMean
* tBodyAccJerkMagStd
* tBodyGyroMagMean
* tBodyGyroMagStd
* tBodyGyroJerkMagMean
* tBodyGyroJerkMagStd
* fBodyAccMeanX
* fBodyAccMeanY
* fBodyAccMeanZ
* fBodyAccStdX
* fBodyAccStdY
* fBodyAccStdZ
* fBodyAccMeanFreqX
* fBodyAccMeanFreqY
* fBodyAccMeanFreqZ
* fBodyAccJerkMeanX
* fBodyAccJerkMeanY
* fBodyAccJerkMeanZ
* fBodyAccJerkStdX
* fBodyAccJerkStdY
* fBodyAccJerkStdZ
* fBodyAccJerkMeanFreqX
* fBodyAccJerkMeanFreqY
* fBodyAccJerkMeanFreqZ
* fBodyGyroMeanX
* fBodyGyroMeanY
* fBodyGyroMeanZ
* fBodyGyroStdX
* fBodyGyroStdY
* fBodyGyroStdZ
* fBodyGyroMeanFreqX
* fBodyGyroMeanFreqY
* fBodyGyroMeanFreqZ
* fBodyAccMagMean
* fBodyAccMagStd
* fBodyAccMagMeanFreq
* fBodyBodyAccJerkMagMean
* fBodyBodyAccJerkMagStd
* fBodyBodyAccJerkMagMeanFreq
* fBodyBodyGyroMagMean
* fBodyBodyGyroMagStd
* fBodyBodyGyroMagMeanFreq
* fBodyBodyGyroJerkMagMean
* fBodyBodyGyroJerkMagStd
* fBodyBodyGyroJerkMagMeanFreq

##Activity Labels.txt
* WALKING (value 1): subject was walking during the test
* WALKING_UPSTAIRS (value 2): subject was walking up a staircase during the test
* WALKING_DOWNSTAIRS (value 3): subject was walking down a staircase during the test
* SITTING (value 4): subject was sitting during the test
* STANDING (value 5): subject was standing during the test
* LAYING (value 6): subject was laying down during the test

##Langkah-langkah untuk mendapatkan data yang clean
### Test Data
* "x_test" yang berisikan variable menggunakan nama kolom pada "feature.txt"
* "y_test" dengan nama kolom pada "activity_label.txt", kemudian dijadikan type data factor dan mapping value dari sebuah angka (1:6) menjadi nama aktivitas dengan menggunakan 'revalue'
* merge subject, acticity dan variable menjadi data frame "test_data"

### Train Data
* "x_train" yang berisikan variable menggunakan nama kolom pada "feature.txt"
* "y_train" dengan nama kolom pada "activity_label.txt", kemudian dijadikan type data factor dan mapping value dari sebuah angka (1:6) menjadi nama aktivitas dengan menggunakan 'revalue'
* merge subject, acticity dan variable menjadi data frame "train_data"

### Merge two Data
* merge "test_data" dan "train_data" menjadi "raw_data" dengan menggunakna cbind, subject diubah menjadi factor data type
* "raw_data" diubah dengan package 'plyr' menjadi type tbl_df untuk mempermudah process data
* Data di grop berdasarkan activity dan subject (untuk activity dan subject yang sama akan di dijumlahkan dan dihitung meannya)




